name: Scrut

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scrut:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup update stable
          rustup default stable

      - name: Install scrut
        uses: cboone/gh-actions/actions/set-up-scrut@844bf31d4ec26df9d0aa531e79d8c3fccf9f0638 # v3.1.0

      - name: Run Scrut tests
        run: scrut test -w . tests
